name: device_features_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.12.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  device_info_plus: ^13.2.0
  image_picker: ^1.2.3
  google_maps_flutter: ^2.18.1
  local_auth: ^3.0.2
  record: ^7.1.1
  audioplayers: ^6.8.1
  path_provider: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0


flutter:

  uses-material-design: true
